### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './data/embedding_50.txt'

### ISSUE THREAD

**Issue by w87777w** [jcsyl/news-analyst#1]
你好  我想问一下
step4_clustering\AP\step2_load_word2vec.py中用到的embedding_50.txt文件没有去哪能找到？

**Comment by jcsyl** [comment]
中文预训练好的词向量 近期我会上传~

**Comment by gugudexiatian** [comment]
求楼主快点上传呀

**Comment by jcsyl** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    文件太大，github 无法上传，需要私发
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                2271545898
                            
                    
                        
                            
                                    2271545898@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 08/1/2019 20:11，gugudexiatian<notifications@github.com> wrote： 


求楼主快点上传呀



—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.
